# 폴더 구조는 .github/workflows 구조로. 근데 파일 이름은 걍 적어도 됨

name: JAVA ONLY DEPLOY

on:
  push:
    branches:
      - docker-java

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일 불러오기
        uses: actions/checkout@v2

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      # Docker 로그인
      - name: 도커 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGINID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd_test:latest .

      # Docker Hub에 이미지 푸시
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd_test:latest
            - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: NCP CLI 다운, NCP CLI & Credentials 세팅
        run: |
          mkdir ncp_cli
          cd ncp_cli
          wget https://www.ncloud.com/api/support/download/files/cli/CLI_1.1.23_20241121.zip
          unzip *.zip
          rm *.zip
          mv CLI_* cli
          cd cli/cli_linux
          sudo apt-get update && sudo apt-get install -y expect

      - name: cli configure 작성 sh 실행
        run: ./ncp_cli_configure.sh

      - name: 됐는지 확인
        run: |
          cd ncp_cli/cli/cli_linux
          .ncloud configure list