# 폴더 구조는 .github/workflows 구조로. 근데 파일 이름은 걍 적어도 됨

name: JAVA ONLY DEPLOY

on:
  push:
    branches:
      - java-only

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일 불러오기
        uses: actions/checkout@v2

      # 근데 말이야.. checkout이라는 라이브러리 써서
      # 내 깃허브 프로젝트 잘 가져온거 맞음....? -> 테스트 해보기
      - name: Checkout Library Test
        run: |
          ls
          pwd

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: Get Actions IP - 이 IP로 EC2 보안그룹 임시 변경
        id: ip
        uses: haythem/public-ip@v1.3

      - name: NCP에 ip 추가..?
        run: |
          ncloud vserver addAccessControlGroupInboundRule \
          --regionCode KR --vpcNo ***04 --accessControlGroupNo ***63 \
          --accessControlGroupRuleList "protocolTypeCode='TCP', ipBlock='${{ steps.ip.outputs.ipv4 }}/32', portRange='22'"